globalThis.process ??= {};
globalThis.process.env ??= {};
import { G as hashString } from "./index_BpQCdXij.mjs";
import { r as requirePerm } from "./authorize_k91w4Tim.mjs";
import { r as requireDb, h as handleError } from "./error_BF6Eb6os.mjs";
import { SchemaRegistry } from "./registry_D7l7v5Xg.mjs";
import { a as generateTypeScript } from "./zod-generator_B2wkOjU4.mjs";
const prerender = false;
const GET = async ({ request, locals }) => {
  const { emdash, user } = locals;
  const dbErr = requireDb(emdash?.db);
  if (dbErr) return dbErr;
  const denied = requirePerm(user, "schema:read");
  if (denied) return denied;
  try {
    const registry = new SchemaRegistry(emdash.db);
    const collections = await registry.listCollections();
    const collectionsWithFields = await Promise.all(
      collections.map(async (c) => {
        const fields = await registry.listFields(c.id);
        return { ...c, fields };
      })
    );
    const url = new URL(request.url);
    const format = url.searchParams.get("format");
    if (format === "typescript") {
      const types = collectionsWithFields.map((c) => generateTypeScript(c)).join("\n\n");
      const header = `// Generated by EmDash CLI
// Do not edit manually - run \`emdash types\` to regenerate

import type { PortableTextBlock } from "emdash";

`;
      return new Response(header + types, {
        status: 200,
        headers: {
          "Content-Type": "text/typescript",
          "Cache-Control": "private, no-store"
        }
      });
    }
    const schemaExport = {
      collections: collectionsWithFields.map((c) => ({
        slug: c.slug,
        label: c.label,
        labelSingular: c.labelSingular,
        description: c.description,
        icon: c.icon,
        supports: c.supports,
        fields: c.fields.map((f) => ({
          slug: f.slug,
          label: f.label,
          type: f.type,
          required: f.required,
          unique: f.unique,
          defaultValue: f.defaultValue,
          validation: f.validation,
          widget: f.widget,
          options: f.options
        }))
      }))
    };
    const version = await hashString(JSON.stringify(schemaExport));
    return new Response(
      JSON.stringify({
        ...schemaExport,
        version
      }),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Cache-Control": "private, no-store",
          "X-Schema-Version": version
        }
      }
    );
  } catch (error) {
    return handleError(error, "Schema export failed", "SCHEMA_EXPORT_ERROR");
  }
};
const _page = /* @__PURE__ */ Object.freeze(/* @__PURE__ */ Object.defineProperty({
  __proto__: null,
  GET,
  prerender
}, Symbol.toStringTag, { value: "Module" }));
const page = () => _page;
export {
  page
};
